name: orbit-ml-rtd-py38
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.1.2
  - python=3.8
  - pandoc
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex<2.0.0
  - nbsphinx
  - sphinxcontrib-napoleon
  - pip:
    - matplotlib
    - IPython
    - numpy>=1.18
    - pandas>=1.0.3
    - matplotlib>=3.3.2
    - scipy>=1.4.1
    - torch>=1.11.0
    - tqdm>=4.36.1
    - seaborn>=0.10.0
    - pyro-ppl>=1.4.0
    - statsmodels>=0.11.1
    - arviz
    - cmdstanpy>=1.0.4
    - setuptools>=42
    - importlib_resources