name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
      #      Currently only checking instead of auto formatting
      # - uses: jpetrucciani/black-check@master
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
          pip install black --upgrade
      - name: black check diff
        run: black --diff .